### ISSUE TITLE
too many arguments error on open

### ISSUE THREAD

**Issue by Xinesi** [minorua/Qgis2threejs#183]
When trying to open the Qgis2threejs plugin in QGIS 3.0.3 (Mac OS 10.14.6) using Python 3.6.5 I'm getting the following:

```
2019-08-28T17:14:58	WARNING	Traceback (most recent call last):
			  File "/Users/theronb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Qgis2threejs/qgis2threejs.py", line 98, in openExporter
			    logMessage("Opening Qgis2threejs Exporter...", False)
			  File "/Users/theronb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Qgis2threejs/qgis2threejstools.py", line 97, in logMessage
			    QgsMessageLog.logMessage(str(message), "Qgis2threejs", Qgis.Warning if warning else Qgis.Info, warning)
			TypeError: QgsMessageLog.logMessage(): too many arguments
```

I have used this plugin previously without problems on this same setup. The only thing that I can think of that has changed since my last use of Qgis2threejs was a Mac OS update. I have tried uninstalling and reinstalling the plugin and receive the following error:

```
An error has occurred while executing Python code: 

TypeError: QgsMessageLog.logMessage(): too many arguments 
Traceback (most recent call last):
  File "/Users/theronb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Qgis2threejs/procalgorithm.py", line 318, in initAlgorithm
    super().initAlgorithm(config)
  File "/Users/theronb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Qgis2threejs/procalgorithm.py", line 94, in initAlgorithm
    self.controller.settings.loadSettingsFromFile(None)
  File "/Users/theronb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Qgis2threejs/exportsettings.py", line 157, in loadSettingsFromFile
    logMessage("Export settings loaded from file:" + filepath, False)
  File "/Users/theronb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Qgis2threejs/qgis2threejstools.py", line 97, in logMessage
    QgsMessageLog.logMessage(str(message), "Qgis2threejs", Qgis.Warning if warning else Qgis.Info, warning)
TypeError: QgsMessageLog.logMessage(): too many arguments


Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
QGIS version: 3.0.3-Girona Girona, exported 

Python Path:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/theronb/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/theronb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/theronb/Library/Application Support/QGIS/QGIS3/profiles/default/python
```

Any help is very much appreciated!

**Comment by minorua** [comment]
Fixed in 41ba7f4 and plugin version 2.3.2 was just released.

This error occurs only in QGIS version 3.0 and I think the version is too old. I will not upload plugin version 2.3.2 to the official plugin repository.

You can download the bug fixed version from the release page:
https://github.com/minorua/Qgis2threejs/releases/tag/v2.3.2
