### ISSUE TITLE
Facing problemas with "Clip DEM with polygon layer" tool

### ISSUE THREAD

**Issue by GeoPontes** [minorua/Qgis2threejs#264]
Hey guys! 

First, thanks creating and maintaning this amazing tool. Secondly, I'd like to report an strange behaviour that I'm experiencing in QGIS 3.16. I have a raster layer obtained through processing of a considerable number of SRTM files (30m of spacial resolution). Also, I have a .shp which delimites the catchment area of a brazillian basin. Both files match in extent and coordinate system. (figure 1)

![fig1](https://user-images.githubusercontent.com/57741984/143902052-dd5fc59b-600e-4e4d-ab0d-b67ef40d8d67.png)

Whenever I try to utilize the "Clip DEM with polygon layer" tool, within "Layer Properties" Menu, the plugin screen frozes (figure 2). I also get an error on QGIS. Actually a yellow bar appears suggesting me to check for erros on the log file (figure 3). The errors, both from Python and Qgis2threejs are shown below. Other presentation set ups work fine. 

![fig2](https://user-images.githubusercontent.com/57741984/143902063-c78fbb94-3161-4307-8d18-4860d3575499.png)

![fig3](https://user-images.githubusercontent.com/57741984/143902064-793f35b6-687d-4afa-a807-65cb27165c93.png)

Could anyone have a hint on what may be the cause of the problem I’m facing? 

Thanks!

ERROR MESSAGE FROM LOG: 

2021-11-29T13:04:50     INFO    Opening Qgis2threejs Exporter...
2021-11-29T13:05:57     WARNING    Traceback (most recent call last):
              File "C:/Users/ALM/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\q3dcontroller.py", line 337, in _processRequests
              self.buildLayer(layer)
              File "C:/Users/ALM/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\q3dcontroller.py", line 253, in buildLayer
              aborted = self._buildLayer(layer)
              File "C:/Users/ALM/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\q3dcontroller.py", line 288, in _buildLayer
              obj = builder.build()
              File "C:/Users/ALM/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\builddem.py", line 202, in build
              geom = self.clipped(self.clip_geometry)
              File "C:/Users/ALM/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\builddem.py", line 299, in clipped
              polys = grid.splitPolygon(clip_geometry)
              File "C:/Users/ALM/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\geometry.py", line 620, in splitPolygon
              for poly in self._splitPolygon(geom):
              File "C:/Users/ALM/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\geometry.py", line 648, in _splitPolygon
              triangles = earcut.earcut(v, data["holes"], data["dimensions"])
              File "C:/Users/ALM/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\earcut\earcut.py", line 39, in earcut
              earcutLinked(outerNode, triangles, dim, minX, minY, invSize)
              File "C:/Users/ALM/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\earcut\earcut.py", line 97, in earcutLinked
              indexCurve(ear, minX, minY, invSize)
              File "C:/Users/ALM/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\earcut\earcut.py", line 357, in indexCurve
              p.z = zOrder(p.x, p.y, minX, minY, invSize)
              File "C:/Users/ALM/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\earcut\earcut.py", line 428, in zOrder
              x = (x | (x              TypeError: unsupported operand type(s) for

**Comment by hollubaun** [comment]
Hi! I keep getting the same error, did you find a solution to this?

**Comment by GeoPontes** [comment]
> Hi! I keep getting the same error, did you find a solution to this?

I managed to solve it by simplifying the vector layer that i was using to crop the raster layer in QGIS2ThreeJS. 

QGIS can perform this vector layer simplification in: Vector -> Geometry -> Simplify (you should test configurations that are suited for your vector layer, but is easir to _oversimplify_ and calibrate from it).

Best of luck!
