### ISSUE TITLE
Sigue el error de representación de capas lineales en Qgis2threejs

### ISSUE THREAD

**Issue by Juanjo1969** [minorua/Qgis2threejs#282]
Hola
Gracias por tu anterior intervención y respuesta Minoru, leí tu correo indicándome que estaba solucionado el bug.
He realizado una comprobación y nuevamente da error, en este caso, la pila de errores obtenido en la consola de Python es el que sigue, lo transcribo literal:

2022-04-07T16:57:29     WARNING    Traceback (most recent call last):
              File "C:/Users/T131465/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\q3dtreeview.py", line 270, in onDoubleClicked
              self.iface.wnd.showLayerPropertiesDialog(layer)
              File "C:/Users/T131465/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\q3dwindow.py", line 296, in showLayerPropertiesDialog
              dialog.showLayerProperties(layer)
              File "C:/Users/T131465/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\q3dwindow.py", line 605, in showLayerProperties
              self.setLayer(layer)
              File "C:/Users/T131465/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\q3dwindow.py", line 581, in setLayer
              self.page = VectorPropertyPage(self, self.layer, self.settings)
              File "C:/Users/T131465/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\proppages.py", line 909, in __init__
              self.tabWidget.setTabVisible(1, False)
             AttributeError: 'QTabWidget' object has no attribute 'setTabVisible'

Ocurre cuando abro una presentación, cuando tengo marcada una capa de líneas, no la representa y la representación que aparece en la parte inferior derecha de la pantalla es como esta:

[Capa vectorial.pdf](https://github.com/minorua/Qgis2threejs/files/8444523/Capa.vectorial.pdf)

La representación en este caso se bloquea y no muestra nada mas en la misma.

Por el contrario, cuando quiero representar una capa de puntos por ejemplo, la representación que aparece en la parte inferior derecha de la pantalla es así:

[Capa de puntos.pdf](https://github.com/minorua/Qgis2threejs/files/8444546/Capa.de.puntos.pdf)

Versión de Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versión de QGIS: 3.10.4-A Coruña A Coruña, 10bc9f2ff2 

Muchas gracias por tu atención.

**Comment by minorua** [comment]
Already fixed in commit 73b212d.
Thanks.
