### ISSUE TITLE
error and crash

### ISSUE THREAD

**Issue by Shemesh** [minorua/Qgis2threejs#298]
hi,
while trying to render a polygon layer the plugin crash with this error.
what does it mean?

WARNING    Traceback (most recent call last):
              File "C:\Users/ooo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\q3dcontroller.py", line 330, in _processRequests
              self.buildLayer(item)
              File "C:\Users/ooo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\q3dcontroller.py", line 236, in buildLayer
              ret = self._buildLayer(layer)
              File "C:\Users/ooo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\q3dcontroller.py", line 275, in _buildLayer
              obj = builder.build()
              File "C:\Users/ooo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\buildvector.py", line 424, in build
              d["geom"] = obj_geom_func(f, f.geometry(self.z_func, mapTo3d, self.useZM, be, self.grid))
              File "C:\Users/ooo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\buildvector.py", line 70, in geometry
              return TINGeometry.fromQgsGeometry(self.geom, zf, transform_func,
              File "C:\Users/ooo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\geometry.py", line 397, in fromQgsGeometry
              pt = geometry.centroid().asPoint()
             ValueError: Null geometry cannot be converted to a point.

**Comment by Shemesh** [comment]
taking a deeper look at the kml (above) seems like the coordinates are all the same.
which actually means nothing.
@minorua - in such case can the plugin ignore it? (rather than crashing)

**Comment by minorua** [comment]
Thanks for your bug report.
