### ISSUE TITLE
Exporting with pipe type line with growing animation effect fails

### ISSUE THREAD

**Issue by minorua** [minorua/Qgis2threejs#331]
```
2024-02-19T14:47:25     WARNING    Traceback (most recent call last):
              File "D:\Users\minorua\QGIS\plugins\Qgis2threejs\exportdialog.py", line 207, in accept
              completed = exporter.export(filepath, cancelSignal=self.ui.pushButton_Cancel.clicked)
              File "D:\Users\minorua\QGIS\plugins\Qgis2threejs\export.py", line 71, in export
              narration = self.settings.narrations()
              File "D:\Users\minorua\QGIS\plugins\Qgis2threejs\exportsettings.py", line 569, in narrations
              for g in self.enabledValidKeyframeGroups():
              File "D:\Users\minorua\QGIS\plugins\Qgis2threejs\exportsettings.py", line 518, in enabledValidKeyframeGroups
              warning_log("Layer '{}': Growing line animation is available with 'Line' and 'Thick Line'.".format(layer.name))
             TypeError: 'NoneType' object is not callable
```

**Comment by minorua** [comment]
Already fixed.
