### ISSUE TITLE
Cannot open plugin settings dialog

### ISSUE THREAD

**Issue by minorua** [minorua/Qgis2threejs#345]
```
2024-07-09T09:36:58     WARNING    Traceback (most recent call last):
              File "D:\Documents\minorua\QGIS\plugins\Qgis2threejs\q3dwindow.py", line 465, in pluginSettings
              dialog = SettingsDialog(self)
              ^^^^^^^^^^^^^^^^^^^^
              File "D:\Documents\minorua\QGIS\plugins\Qgis2threejs\pluginsettings.py", line 47, in __init__
              parser = configparser.SafeConfigParser()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```

**Comment by minorua** [comment]
Python in OSGeo4W was updated from 3.9.18 to 3.12.3 in April.

https://lists.osgeo.org/pipermail/qgis-user/2024-April/054334.html
