### ISSUE TITLE
V2.8 Install Error- No module named 'Qgis2threejs-2

### ISSUE THREAD

**Issue by Yakwrangler** [minorua/Qgis2threejs#361]
Loading 2.8 plugin into 3.34.11-Prizren from ZIP file produces the following error ...

2024-10-30T09:02:10     CRITICAL    Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS33~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
              __import__(packageName)
              File "C:\PROGRA~1/QGIS33~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             ModuleNotFoundError: No module named 'Qgis2threejs-2'

**Comment by minorua** [comment]
The version 2.8 source code downloaded from GitHub is stored in a directory named `Qgis2threejs-2.8` within the zip file. To load the plugin correctly, you need to rename this directory to `Qgis2threejs`. Python builtin `__import__` function cannot import modules with names that contain a period.
