### ISSUE TITLE
Error *cannot convert float NaN to integer*

### ISSUE THREAD

**Issue by pcav** [minorua/Qgis2threejs#39]
I'm consistently getting the following error, even experimenting with different options and setting:

An error has occured while executing Python code:

Traceback (most recent call last):
  File "/home/paolo/.qgis2/python/plugins/Qgis2threejs/qgis2threejsdialog.py", line 411, in run
    ret = exportToThreeJS(export_settings, self.iface.legendInterface(), self.objectTypeManager, self.progress)
  File "/home/paolo/.qgis2/python/plugins/Qgis2threejs/qgis2threejsmain.py", line 354, in exportToThreeJS
    writeMultiResDEM(writer, demProperties, progress)
  File "/home/paolo/.qgis2/python/plugins/Qgis2threejs/qgis2threejsmain.py", line 753, in writeMultiResDEM
    writer.write("bl.data = [{0}];\n".format(",".join(map(gdal2threejs.formatValue, dem_values))))
  File "/home/paolo/.qgis2/python/plugins/Qgis2threejs/gdal2threejs.py", line 97, in formatValue
    if int(val) == val:
ValueError: cannot convert float NaN to integer

**Comment by pcav** [comment]
Cannot replicate it when starting from a clean config. It may be due to other plugins. Feel free to close it.
Sorry for the noise.
