### ISSUE TITLE
Python error that seems to be due to GDAL update (OSGeo4W64)

### ISSUE THREAD

**Issue by minorua** [minorua/Qgis2threejs#63]
Any DEMs cannot export.

```
Traceback (most recent call last):
  File "D:\Users\minorua\.qgis2\python\developing_plugins\Qgis2threejs\qgis2threejsdialog.py", line 544, in run
    ret = exportToThreeJS(export_settings, self.iface.legendInterface(), self.objectTypeManager, self.progress)
  File "D:\Users\minorua\.qgis2\python\developing_plugins\Qgis2threejs\export.py", line 238, in exportToThreeJS
    writer = ThreejsJSWriter(settings, objectTypeManager, bool(settings.exportMode == ExportSettings.PLAIN_MULTI_RES))
  File "D:\Users\minorua\.qgis2\python\developing_plugins\Qgis2threejs\export.py", line 91, in __init__
    self.demProvider = settings.demProvider()
  File "D:\Users\minorua\.qgis2\python\developing_plugins\Qgis2threejs\exportsettings.py", line 142, in demProvider
    return self.demProviderByLayerId(layerId)
  File "D:\Users\minorua\.qgis2\python\developing_plugins\Qgis2threejs\exportsettings.py", line 209, in demProviderByLayerId
    return GDALDEMProvider(layer.source(), str(self.crs.toWkt()), source_wkt=str(layer.crs().toWkt()))    # use CRS set to the layer in QGIS
  File "D:\Users\minorua\.qgis2\python\developing_plugins\Qgis2threejs\qgis2threejscore.py", line 114, in __init__
    self.ds.SetProjection(str(source_wkt))
AttributeError: 'NoneType' object has no attribute 'SetProjection'
```
OSGeo4W64, QGIS 2.8.6, GDAL 1.11.3

**Comment by minorua** [comment]
`gdal.AllRegister()` should be called.

**Comment by minorua** [comment]
```
>>>gdal.VersionInfo()
'2000200'
```

**Comment by minorua** [comment]
Reinstalling `gdal-python` package version `1.11.3-1` clears away the error.

**Comment by minorua** [comment]
No problem with `qgis` package version `2.14.0-1`.
