### ISSUE TITLE
error when trying to make a polygon with Z coordinate

### ISSUE THREAD

**Issue by baditaflorin** [minorua/Qgis2threejs#71]
2016-06-07T19:10:25	1	Traceback (most recent call last):
			  File "C:/Users/florinb/.qgis2/python/plugins\Qgis2threejs\qgis2threejsdialog.py", line 544, in run
			    ret = exportToThreeJS(export_settings, self.iface.legendInterface(), self.objectTypeManager, self.progress)
			  File "C:/Users/florinb/.qgis2/python/plugins\Qgis2threejs\export.py", line 271, in exportToThreeJS
			    writeVectors(writer, legendInterface, progress)
			  File "C:/Users/florinb/.qgis2/python/plugins\Qgis2threejs\export.py", line 850, in writeVectors
			    for feat in layer.features(request, clipGeom):
			  File "C:/Users/florinb/.qgis2/python/plugins\Qgis2threejs\export.py", line 778, in features
			    feat.geom = self.geomClass.fromQgsGeometry(geom, z_func, transform_func, self.hasLabel())
			  File "C:/Users/florinb/.qgis2/python/plugins\Qgis2threejs\geometry.py", line 228, in fromQgsGeometry
			    pt = QgsGeometry.fromPolygon(polygon).centroid().asPoint()
			AttributeError: 'NoneType' object has no attribute 'asPoint'

**Comment by baditaflorin** [comment]
From what i see the bug happens only when i change the Addend value

![image](https://cloud.githubusercontent.com/assets/2330999/15865642/3dd11150-2ce4-11e6-886b-9e31e9aac7df.png)

**Comment by minorua** [comment]
Thanks for the report!
