### ISSUE TITLE
Python error when exporting a polygon layer with Qgs25DRenderer selected

### ISSUE THREAD

**Issue by minorua** [minorua/Qgis2threejs#77]
Pythonコードの実行中にエラーが発生しました: 

TypeError: Qgs25DRenderer.symbolForFeature(QgsFeature, QgsRenderContext): not enough arguments 
Traceback (most recent call last):
  File "D:/Users/minorua/.qgis2/python/plugins\Qgis2threejs\qgis2threejsdialog.py", line 544, in run
    ret = exportToThreeJS(export_settings, self.iface.legendInterface(), self.objectTypeManager, self.progress)
  File "D:/Users/minorua/.qgis2/python/plugins\Qgis2threejs\export.py", line 271, in exportToThreeJS
    writeVectors(writer, legendInterface, progress)
  File "D:/Users/minorua/.qgis2/python/plugins\Qgis2threejs\export.py", line 852, in writeVectors
    if not obj_mod.write(writer, layer, feat):   # writer.writeFeature(layer, feat, obj_mod)
  File "D:/Users/minorua/.qgis2/python/plugins\Qgis2threejs\objects\polygon_basic.py", line 97, in write
    vals = feat.propValues()
  File "D:/Users/minorua/.qgis2/python/plugins\Qgis2threejs\export.py", line 609, in propValues
    return self.prop.values(self.feat)
  File "D:/Users/minorua/.qgis2/python/plugins\Qgis2threejs\propertyreader.py", line 187, in values
    vals.append(self._readColor(widgetValues, f, widgetType == StyleWidget.OPTIONAL_COLOR))
  File "D:/Users/minorua/.qgis2/python/plugins\Qgis2threejs\propertyreader.py", line 89, in _readColor
    symbol = self.layer.rendererV2().symbolForFeature(f)
TypeError: Qgs25DRenderer.symbolForFeature(QgsFeature, QgsRenderContext): not enough arguments

Pythonバージョン: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGISバージョン: 2.16.0-Nødebo Nødebo, d0b3e39

**Comment by rubo77** [comment]
I got this too on 1.4.2

**Comment by chojje** [comment]
@rubo77 Thanks, this resolved the issue for me!

**Comment by minorua** [comment]
Fixed.
