### ISSUE TITLE
 TypeError: QgsNullSymbolRenderer.symbolForFeature(QgsFeature, QgsRenderContext): not enough arguments

### ISSUE THREAD

**Issue by robinpaulson** [minorua/Qgis2threejs#84]
I get the following errors when I render:
2016-09-22T15:01:30 1   warning:/home/robin/.qgis2/python/plugins/Qgis2threejs/propertyreader.py:89: DeprecationWarning: QgsFeatureRendererV2.symbolForFeature() is deprecated
              symbol = self.layer.rendererV2().symbolForFeature(f)

```
        traceback:  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/qgis2threejs.py", line 109, in run
            ret = dialog.exec_()
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/qgis2threejsdialog.py", line 544, in run
            ret = exportToThreeJS(export_settings, self.iface.legendInterface(), self.objectTypeManager, self.progress)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 271, in exportToThreeJS
            writeVectors(writer, legendInterface, progress)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 852, in writeVectors
            if not obj_mod.write(writer, layer, feat):   # writer.writeFeature(layer, feat, obj_mod)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/objects/line_basic.py", line 67, in write
            vals = feat.propValues()
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 609, in propValues
            return self.prop.values(self.feat)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/propertyreader.py", line 187, in values
            vals.append(self._readColor(widgetValues, f, widgetType == StyleWidget.OPTIONAL_COLOR))
```

2016-09-22T15:01:30 1   warning:/home/robin/.qgis2/python/plugins/Qgis2threejs/propertyreader.py:99: DeprecationWarning: QgsSymbolLayerV2.dataDefinedProperty() is deprecated
              expr = sl.dataDefinedProperty("color")

```
        traceback:  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/qgis2threejs.py", line 109, in run
            ret = dialog.exec_()
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/qgis2threejsdialog.py", line 544, in run
            ret = exportToThreeJS(export_settings, self.iface.legendInterface(), self.objectTypeManager, self.progress)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 271, in exportToThreeJS
            writeVectors(writer, legendInterface, progress)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 852, in writeVectors
            if not obj_mod.write(writer, layer, feat):   # writer.writeFeature(layer, feat, obj_mod)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/objects/line_basic.py", line 67, in write
            vals = feat.propValues()
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 609, in propValues
            return self.prop.values(self.feat)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/propertyreader.py", line 187, in values
            vals.append(self._readColor(widgetValues, f, widgetType == StyleWidget.OPTIONAL_COLOR))
```

2016-09-22T15:01:30 1   warning:/home/robin/.qgis2/python/plugins/Qgis2threejs/propertyreader.py:120: DeprecationWarning: QgsFeatureRendererV2.symbolForFeature() is deprecated
              symbol = self.layer.rendererV2().symbolForFeature(f)

```
        traceback:  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/qgis2threejs.py", line 109, in run
            ret = dialog.exec_()
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/qgis2threejsdialog.py", line 544, in run
            ret = exportToThreeJS(export_settings, self.iface.legendInterface(), self.objectTypeManager, self.progress)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 271, in exportToThreeJS
            writeVectors(writer, legendInterface, progress)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 852, in writeVectors
            if not obj_mod.write(writer, layer, feat):   # writer.writeFeature(layer, feat, obj_mod)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/objects/line_basic.py", line 67, in write
            vals = feat.propValues()
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 609, in propValues
            return self.prop.values(self.feat)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/propertyreader.py", line 198, in values
            vals.append(self._readTransparency(widgetValues, f))
```

2016-09-22T15:01:30 1   warning:/home/robin/.qgis2/python/plugins/Qgis2threejs/propertyreader.py:127: DeprecationWarning: QgsSymbolLayerV2.dataDefinedProperty() is deprecated
              expr = sl.dataDefinedProperty("color")

```
        traceback:  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/qgis2threejs.py", line 109, in run
            ret = dialog.exec_()
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/qgis2threejsdialog.py", line 544, in run
            ret = exportToThreeJS(export_settings, self.iface.legendInterface(), self.objectTypeManager, self.progress)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 271, in exportToThreeJS
            writeVectors(writer, legendInterface, progress)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 852, in writeVectors
            if not obj_mod.write(writer, layer, feat):   # writer.writeFeature(layer, feat, obj_mod)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/objects/line_basic.py", line 67, in write
            vals = feat.propValues()
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 609, in propValues
            return self.prop.values(self.feat)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/propertyreader.py", line 198, in values
            vals.append(self._readTransparency(widgetValues, f))
```

2016-09-22T15:01:31 1   warning:/home/robin/.qgis2/python/plugins/Qgis2threejs/propertyreader.py:147: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
              logMessage(u'{0} (value: {1})'.format(e.message, unicode(val)))

```
        traceback:  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/qgis2threejs.py", line 109, in run
            ret = dialog.exec_()
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/qgis2threejsdialog.py", line 544, in run
            ret = exportToThreeJS(export_settings, self.iface.legendInterface(), self.objectTypeManager, self.progress)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 271, in exportToThreeJS
            writeVectors(writer, legendInterface, progress)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 852, in writeVectors
            if not obj_mod.write(writer, layer, feat):   # writer.writeFeature(layer, feat, obj_mod)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/objects/point_basic.py", line 57, in write
            vals = feat.propValues()
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 609, in propValues
            return self.prop.values(self.feat)
          File "/home/robin/.qgis2/python/plugins/Qgis2threejs/propertyreader.py", line 229, in values
            val = self.toFloat(f.attribute(fieldName)) * self.toFloat(widgetValues["editText"])
```

I can't isolate which aspect of the layer in question is causing the problem.

QGIS 2.16.2 + ubuntugis-unstable, Ubuntu Xenial

**Comment by robinpaulson** [comment]
Hmm, more errors, from a different layer:
2016-09-22T15:17:30	1	Traceback (most recent call last):
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/qgis2threejsdialog.py", line 544, in run
			    ret = exportToThreeJS(export_settings, self.iface.legendInterface(), self.objectTypeManager, self.progress)
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 271, in exportToThreeJS
			    writeVectors(writer, legendInterface, progress)
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 852, in writeVectors
			    if not obj_mod.write(writer, layer, feat):   # writer.writeFeature(layer, feat, obj_mod)
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/objects/line_basic.py", line 67, in write
			    vals = feat.propValues()
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 609, in propValues
			    return self.prop.values(self.feat)
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/propertyreader.py", line 187, in values
			    vals.append(self._readColor(widgetValues, f, widgetType == StyleWidget.OPTIONAL_COLOR))
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/propertyreader.py", line 89, in _readColor
			    symbol = self.layer.rendererV2().symbolForFeature(f)
			TypeError: QgsNullSymbolRenderer.symbolForFeature(QgsFeature, QgsRenderContext): not enough arguments
			
2016-09-22T15:18:27	1	Traceback (most recent call last):
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/qgis2threejsdialog.py", line 544, in run
			    ret = exportToThreeJS(export_settings, self.iface.legendInterface(), self.objectTypeManager, self.progress)
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 271, in exportToThreeJS
			    writeVectors(writer, legendInterface, progress)
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 852, in writeVectors
			    if not obj_mod.write(writer, layer, feat):   # writer.writeFeature(layer, feat, obj_mod)
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/objects/line_basic.py", line 67, in write
			    vals = feat.propValues()
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 609, in propValues
			    return self.prop.values(self.feat)
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/propertyreader.py", line 187, in values
			    vals.append(self._readColor(widgetValues, f, widgetType == StyleWidget.OPTIONAL_COLOR))
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/propertyreader.py", line 89, in _readColor
			    symbol = self.layer.rendererV2().symbolForFeature(f)
			TypeError: QgsNullSymbolRenderer.symbolForFeature(QgsFeature, QgsRenderContext): not enough arguments
			
2016-09-22T15:18:40	1	Traceback (most recent call last):
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/qgis2threejsdialog.py", line 544, in run
			    ret = exportToThreeJS(export_settings, self.iface.legendInterface(), self.objectTypeManager, self.progress)
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 271, in exportToThreeJS
			    writeVectors(writer, legendInterface, progress)
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 852, in writeVectors
			    if not obj_mod.write(writer, layer, feat):   # writer.writeFeature(layer, feat, obj_mod)
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/objects/line_basic.py", line 67, in write
			    vals = feat.propValues()
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 609, in propValues
			    return self.prop.values(self.feat)
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/propertyreader.py", line 187, in values
			    vals.append(self._readColor(widgetValues, f, widgetType == StyleWidget.OPTIONAL_COLOR))
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/propertyreader.py", line 89, in _readColor
			    symbol = self.layer.rendererV2().symbolForFeature(f)
			TypeError: QgsNullSymbolRenderer.symbolForFeature(QgsFeature, QgsRenderContext): not enough arguments
			
2016-09-22T15:36:28	1	Traceback (most recent call last):
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/qgis2threejsdialog.py", line 544, in run
			    ret = exportToThreeJS(export_settings, self.iface.legendInterface(), self.objectTypeManager, self.progress)
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 271, in exportToThreeJS
			    writeVectors(writer, legendInterface, progress)
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 852, in writeVectors
			    if not obj_mod.write(writer, layer, feat):   # writer.writeFeature(layer, feat, obj_mod)
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/objects/line_basic.py", line 67, in write
			    vals = feat.propValues()
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/export.py", line 609, in propValues
			    return self.prop.values(self.feat)
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/propertyreader.py", line 187, in values
			    vals.append(self._readColor(widgetValues, f, widgetType == StyleWidget.OPTIONAL_COLOR))
			  File "/home/robin/.qgis2/python/plugins/Qgis2threejs/propertyreader.py", line 89, in _readColor
			    symbol = self.layer.rendererV2().symbolForFeature(f)
			TypeError: QgsRuleBasedRendererV2.symbolForFeature(QgsFeature, QgsRenderContext): not enough arguments

**Comment by minorua** [comment]
Fixed.
